# Generated by Django 2.1.7 on 2019-08-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20190818_0621'),
        ('thesis', '0002_auto_20190818_0556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Coordinator',
        ),
    ]
